name: Create release
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{secrets.GIT_PUSH_TOKEN}}
      - name: Create release commit
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y git-buildpackage 
          export DEBEMAIL="dev@radxa.com"
          export DEBFULLNAME='"Radxa Computer Co., Ltd"'
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          make lib
      - name: Test
        run: |
          make test
          sudo apt install -y binfmt-support qemu-user-static podman
          .github/container/build-deb
      - name: Push
        run: |
          git push
